### ISSUE TITLE
Add to Watchlist

### ISSUE THREAD

**Issue by sahedw** [sahedw/capstone-movie-app#10]
## Value Proposition

**As a user** 
**I want to add a movie to my watchlist**
**so that I can potentially find all my watchlist movies in one place**
​

## Description

<img width="321" alt="Bildschirm­foto 2023-03-17 um 11 51 43" src="https://user-images.githubusercontent.com/122886715/225885664-68f98bd1-2536-4504-8e47-10759ac48dc1.png">

## Acceptance Criteria

- [x] Im able to add to watchlist once after I clicked on a movie
- [x] Some indicator is visible that shows if the movie is marked or unmarked
      ​
## Tasks

- [x] Create a button on the movie detail page 
- [x] Create a function to toggle add and delete from watchlist
- [x] Change text of button depending on the state of the movie in the watchlist

## Complexity

M
