### ISSUE TITLE
My Favorites Page

### ISSUE THREAD

**Issue by sahedw** [sahedw/capstone-movie-app#12]
## Value Proposition

**As a user** 
**I want to have access to all my movies that I marked as my favorite**
**so that I can easily look at all my favorite movies in one place without distraction or a complicated way**  
​

## Description

<img width="304" alt="Bildschirm­foto 2023-03-17 um 12 08 46" src="https://user-images.githubusercontent.com/122886715/225889059-504732ba-44f8-4a2d-94fc-5cd124e57e93.png">

## Acceptance Criteria

- [ ] The marked movie is shown on a separate page
- [ ] I can switch to my favorites page
- [ ] Every marked movie is shown with a movie poster
- [ ] I can click on the movie poster to have access to more details

## Tasks

- [ ] Display the favorites on the favorites page
- [ ] Maybe filter the original array/useState or use a different state where the movies are saved
- [ ] Display the posters only in a grid
      ​

## Complexity

M
