### ISSUE TITLE
Cinema Page and Navbar Icon

### ISSUE THREAD

**Issue by sahedw** [sahedw/capstone-movie-app#24]
## Value Proposition

**As a user**
**I want to see have a page where I can see which movies are currently in cinema**
**so that I don't need to exit the app and have everything in one place**
​

## Description

<img width="291" alt="Bildschirm­foto 2023-03-24 um 13 52 51" src="https://user-images.githubusercontent.com/122886715/227527380-8af9d75c-9aab-426e-b844-7aa07d667150.png">

## Acceptance Criteria

- [x] You can click in the navbar on the cinema icon
- [x] You get all movies display which are currently in cinemas 
- [x] You can also click on them and get to the movie details
      ​

## Tasks

- [x] Find fitting icon
- [x] Create new route/page with next.js
- [x] Adapt the function for highlighting the current icon
- [x] Fetch the movies which are currently in cinemas 
- [x] Display in a grid
- [x] Add same function with moviedetail component
      ​

## Complexity

M
