### ISSUE TITLE
Structured Homepage 1/3

### ISSUE THREAD

**Issue by sahedw** [sahedw/capstone-movie-app#25]
## Value Proposition

**As a user**
**I want to have a visually appealing search function and greetings text**
**so that it's fun to use the search function and to feel appreciated**
​

## Description

<img width="338" alt="Bildschirm­foto 2023-03-24 um 14 28 22" src="https://user-images.githubusercontent.com/122886715/227534577-7f4cf79d-769c-470f-98af-11debd314a5c.png">

## Acceptance Criteria

- [ ] Text with a greeting is displayed
- [ ] I can search for movies in the middle of the page
- [ ] Search gets submitted by pressing enter or by clicking on the magnifying glass
      ​

## Tasks

- [ ] Heading with text for greeting
- [ ] Display flex for centered input form
- [ ] Make the submit button the icon and place the icon within the input form
      ​

## Complexity

S-M
