### ISSUE TITLE
Structured Homepage 2/3

### ISSUE THREAD

**Issue by sahedw** [sahedw/capstone-movie-app#26]
## Value Proposition

**As a user**
**I want to have a suggestion as what to watch every time I visit the app** 
**so that I get a random pick of my watchlist picked for me without actually 'searching' for movies to watch**
​

## Description
​
<img width="335" alt="Bildschirm­foto 2023-03-24 um 14 36 49" src="https://user-images.githubusercontent.com/122886715/227536408-f313545e-ecc9-490d-b9f2-45983d68c8bd.png">

## Acceptance Criteria

- [ ] On the homepage the suggested movie poster is seen
- [ ] A quick overview like actually searching a movie is shown for the random movie
- [ ] Text is shown which playfully suggests the movie
- [ ] Clicking the movie brings you to more details
      ​

## Tasks

- [ ] Write a playful header
- [ ] Also display it centered with flexbox
- [ ] Use the movie component to display the quick overview
- [ ] Use the moviedetail component if the user clicks on the movie
      ​

## Complexity

M
