### ISSUE TITLE
Structured Homepage 3/3

### ISSUE THREAD

**Issue by sahedw** [sahedw/capstone-movie-app#27]
## Value Proposition

**As a user**
**I want to have a sneak peek of top trending movies right now**
**so that I can also have suggestions as what to watch and also see what most people are watching right now**
​

## Description

<img width="335" alt="Bildschirm­foto 2023-03-24 um 14 50 14" src="https://user-images.githubusercontent.com/122886715/227541104-fa074d4d-9759-48fb-b616-3489f109e45b.png">

## Acceptance Criteria

- [x] Text is shown which indicates what kind of movies are display
- [x] The movies are shown as only posters
- [x] Show top nine trending movies
      ​

## Tasks

- [x] Add a heading which explains that these are trending movies
- [x] use maybe grid or flexbox
- [x] Only display the movie poster
      ​

## Complexity

L

**Comment by nikokreissl** [comment]
Looking good! 😊
Just one note regarding acceptance criteria - as I would say should the statements be here clear what and how it is going to work otherwise during QA questions will be raised. So in your case you should decide if you want to add scroll for the movies in this US or not - and thinking of MVP maybe skipping it would be better. 😉
Keep up the good work!

**Comment by sahedw** [comment]
Appreciate it! I guess you're right, skipping it for now would be the better and smarter option 🙌🏼
