### ISSUE TITLE
Movie YouTube Trailer 

### ISSUE THREAD

**Issue by sahedw** [sahedw/capstone-movie-app#28]
## Value Proposition

**As a user**
**I want to be able to watch the trailer in the app**
**so that I can get additionally some scenes of the movie for a better impression**
​

## Description

<img width="365" alt="Bildschirm­foto 2023-03-24 um 15 05 04" src="https://user-images.githubusercontent.com/122886715/227543247-04981874-7cde-4db4-a198-eb1144e1d58b.png">

## Acceptance Criteria

- [ ] Button/Text is shown on the page which displays further movie details
- [ ] Clicking on it brings up the trailer
- [ ] Being able to close and control the trailer
      ​

## Tasks

- [ ] Create button or text which display the trailer
- [ ] React-Youtube or React-Player are good npm packages. More research.
- [ ] 
      ​

## Complexity

L

**Comment by nikokreissl** [comment]
Not sure which information the API provides but maybe using an `iFrame` is reasonable? 🤔
It came to my mind since it is a common way to embed videos coming from another source 😊

**Comment by sahedw** [comment]
Yeah the above mentioned packages(React-Youtube or React-Player) both use the iFrame AFAIK
