### ISSUE TITLE
Switching Grid or List Layout

### ISSUE THREAD

**Issue by sahedw** [sahedw/capstone-movie-app#29]
## Value Proposition

**As a user**
**I want to be able to choose how I want my watchlist to be displayed**
**so that I can see more details if I want or be able to only see the poster for my visual appeal**
​

## Description

<img width="324" alt="Bildschirm­foto 2023-03-24 um 15 20 25" src="https://user-images.githubusercontent.com/122886715/227550552-24ec4b77-fccf-4c92-89af-3e68170a6982.png">

## Acceptance Criteria

- [ ] When on the watchlist you can see the grid and list option on the page
- [ ] Pressing grid displays the movies in a grid as posters
- [ ] Pressing list shows the movies as a list with a quick overview
- [ ] When pressing on one, the option gets disabled
      ​

## Tasks

- [ ] Create text/button for the switch
- [ ] Design the grid or list
- [ ] Make it dynamic with conditional rendering
- [ ] Disable the button which is currently active if its a button
      ​

## Complexity

M
