### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by sahedw** [sahedw/capstone-movie-app#3]
## Value Proposition

**As a user**
**I want to have access to every page through a navigation**
**so that I'm able to jump between different pages**  
​

## Description
​
<img width="296" alt="Bildschirm­foto 2023-03-15 um 14 17 48" src="https://user-images.githubusercontent.com/122886715/225320461-1c3e9048-259d-4feb-96cf-fb21c5a1d71c.png">

## Acceptance Criteria

- [x] A fixed navigation/box is visible at the bottom of the page
- [x] The navigation leads to different pages if clicked
- [x] I can find the navigation on every page 
- [x] I can see all the content and nothing is hidden behind the navbar
      ​

## Tasks

- [x] Create a navigation component which consists of a nav, ul and li elements
- [x] Add text to every list element which derives from the page it leads to 
- [x] Wrap the text within the navigation component with links that lead the user to the desired page
- [x] Add the navigation component to every page
- [x] Highlight navbar icon & text if currently on that page
- [x] Push the site higher with margin-buttom, so nothing is hidden behind the navbar

      ​
