### ISSUE TITLE
My Watched Page

### ISSUE THREAD

**Issue by sahedw** [sahedw/capstone-movie-app#30]
## Value Proposition

**As a user**
**I want to keep track of the movies I already watched**
**so that I can look all my watched movies anytime I want up**
​

## Description
​
<img width="320" alt="Bildschirm­foto 2023-03-24 um 15 28 22" src="https://user-images.githubusercontent.com/122886715/227553488-9ea15c7f-a38a-43c9-866c-f6ffcc733d24.png">

## Acceptance Criteria

- [ ] The Navbar shows a watched button
- [ ] Clicking on it leads to my watched page
- [ ] The Page shows every movie which is marked as watched
- [ ] Clicking on the movie shows details
      ​

## Tasks

- [ ] Create another Page
- [ ] Add icon to the navbar
- [ ] Icon leads to the page with next.js
- [ ] Uses the movie detail component for the movies if clicked
      ​

## Complexity

M
