### ISSUE TITLE
Mark as Watched

### ISSUE THREAD

**Issue by sahedw** [sahedw/capstone-movie-app#31]
## Value Proposition

**As a user**
**I want to mark movies as already watched**
**so that I can also keep track of watched movies**
​

## Description
​
<img width="328" alt="Bildschirm­foto 2023-03-24 um 15 40 06" src="https://user-images.githubusercontent.com/122886715/227556237-19a3a8d7-db00-492a-ab9e-aac34dc4009e.png">

## Acceptance Criteria

- [x] Im able to add to watchlist once after I clicked on a movie
- [x] Some indicator is visible that shows if the movie is marked or unmarked

## Tasks

- [x] Create a button on the movie detail page
- [x] Create a function to toggle add and delete from watched
- [x] Change text of button depending on the state of the movie in the watched list​
      ​

## Complexity

M
