### ISSUE TITLE
Refactoring and unused code

### ISSUE THREAD

**Issue by sahedw** [sahedw/capstone-movie-app#39]
## Value Proposition

**As a developer**
**I want to have clean code, no repetitions and no unused code** ... (describe the goal)  
**so that my app looks like a best practise app** ... (describe the reason)  
​

## Description

Deleting console.logs, unnecessary comments for future features and no repetitions.
​

## Acceptance Criteria

- [ ] Cleaner Code
      ​

## Tasks

- [ ] Search for console.logs and delete them
- [ ] Search for comments and delete them
- [ ] Look for unnecessary repitions
      ​

## Complexity

S

**Comment by nikokreissl** [comment]
The value proposition shows the text from the template, e.g.  `... (describe the goal)`. I think you can remove it.
And at `Acceptance Criteria` you could maybe write `No console.logs() left in code` and `No comments left in code` as additional items. 🙂
Other than that good user story 🚀
