### ISSUE TITLE
Movie Availability buy, rent or flatrate

### ISSUE THREAD

**Issue by sahedw** [sahedw/capstone-movie-app#42]
## Value Proposition

**As a user** 
**I want to see where the movie can be bought, rented or watched with a flatrate** 
**so that I can instantly now how to watch it and where** 
​

## Description

<img width="291" alt="Bildschirm­foto 2023-03-30 um 15 28 19" src="https://user-images.githubusercontent.com/122886715/228851660-76e24f42-7c01-4b69-a582-77a3341fc0c5.png">

## Acceptance Criteria

- [ ] On the bottom of the movie page there should be availability of the movie
- [ ] It should show where you can buy it
- [ ] It should show where you can rent it 
- [ ] It should show where you can watch it with a flatrate
- [ ] should show two or three places max. per option
      ​

## Tasks

- [ ] Use the existing fetched data for showing the flatrate availability 
- [ ] Display additionally the rent and buy with the already fetched data
      ​

## Complexity

XS
