### ISSUE TITLE
Settingspage with Dark Mode and Availability

### ISSUE THREAD

**Issue by sahedw** [sahedw/capstone-movie-app#43]
## Value Proposition

**As a user** 
**I want to change some settings like the color theme like a dark mode or light mode and an option which availability it should show me in the movie details**  
**so that I can use the app how I want with the information that I regard as relevant for me**
​

## Description

<img width="267" alt="Bildschirm­foto 2023-03-30 um 15 39 15" src="https://user-images.githubusercontent.com/122886715/228856086-12ffc283-5d82-4300-844e-98d729ed91ae.png">
<img width="269" alt="Bildschirm­foto 2023-03-30 um 15 41 33" src="https://user-images.githubusercontent.com/122886715/228856081-1d089f4d-1ab9-4501-94d6-27fd80c5795b.png">

## Acceptance Criteria

- [x] I should see a gear icon on the landing page 
- [x] Clicking on it leads me to a settings page
- [x] Here I can switch to dark mode
- [x] Also decide which availability should get displayed in the movie details 
      ​

## Tasks

- [x] Search fitting icon
- [x] Link to newly created page with Link Element and next.js routing
- [x] Here track dark mode with a state and if clicked color should switch 
- [x] Same conditional rendering for the movie detail component with a state that can be set by the user in the settings page regarding the prefered availability display
      ​

## Complexity

XL
