### ISSUE TITLE
TrendingMovies Details

### ISSUE THREAD

**Issue by sahedw** [sahedw/capstone-movie-app#44]
## Value Proposition

**As a user** 
**I want to click on the trending movies and see further information**
**so that I save me the hussle of guessing the name with the movie poster alone and searching it** 
​

## Description
​
<img width="270" alt="Bildschirm­foto 2023-03-30 um 15 50 47" src="https://user-images.githubusercontent.com/122886715/228857920-32c48b70-b082-4413-b4d4-7052db7b467f.png">

## Acceptance Criteria

- [x] Clicking on a movie in the trending movies leads to the movie details
      ​
## Tasks

- [x] Look if its possible with existing movie detail component 
- [x] If not create same component with slight variation
      ​

## Complexity

M
