### ISSUE TITLE
Upcoming movies in Cinema

### ISSUE THREAD

**Issue by sahedw** [sahedw/capstone-movie-app#48]
## Value Proposition

**As a user** ... (User, Author, logged in User...)  
**I want to have the option to decide if I want see upcoming movies in the cinema page or currently playing ones** 
**so that I can see what will be available in the cinemas in a few day/weeks/months** 
​

## Description
​
<img width="286" alt="Bildschirm­foto 2023-03-31 um 16 41 37" src="https://user-images.githubusercontent.com/122886715/229155330-3292b1ba-52e0-4a7b-ac4e-5e443e54372f.png">

## Acceptance Criteria

- [ ] On the Cinema Page there should be the option to click on playing and upcoming
- [ ] Clicking on playing shows whats currently playing in cinemas
- [ ] Clicking on unpcoming shows what will be cinemas in the future
- [ ] Clicking on a movie should lead to the movie details
      ​

## Tasks

- [ ] New fetch of upcoming movies from API
- [ ] Create button for conditional rendering of playing movies and upcoming
- [ ] Write the function to handle the change
- [ ] MovieDetail for clicking on movies
      ​

## Complexity

M
