### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by sahedw** [sahedw/capstone-movie-app#49]
## Value Proposition

**As a user** 
**I want to look through more than 20 search results and see pages of search results**
**so that I can find my desired movie**

## Description

<img width="271" alt="Bildschirm­foto 2023-04-03 um 09 14 42" src="https://user-images.githubusercontent.com/122886715/229439815-a98a985d-eeb2-4800-89e1-3a55cae0d748.png">

## Acceptance Criteria

- [ ] You see a button after you searched for a movie which says "Next Page" and "Previous Page"
- [ ] Clicking on it refreshes the search results and shows you 20 more movies with your search term.
- [ ] You're able to also go back to the previous search results page.
      ​

## Tasks

- [ ] Modify the current fetch with the search term
- [ ] Track the page of the fetch with a state 
- [ ] Use the state to write a function which increments or decrements the state 
- [ ] Be careful of the useEffect dependency array
      ​

## Complexity

L

**Comment by nikokreissl** [comment]
Great user story and really nice designs 🚀😊
Three things came to my mind when reading this US which you might want to consider as additional UX enahncement in this or another US:
- Adding logic that if the user can not go to next page if there are no more movies or back if the use is on page 1 would be nice 
- Currently when searching a movie and no results are found the user is brought to an empty page. In general a note what the user searched for would be nice so he can see directly if there are maybe any typos and additionally some "nice" empty state message would be cool if there are no results to be shown due to the search request
- Some information how many movies were found in total would be great but not sure if your API is providing this information respectively if you can show it like this with pagination. Like this the user knows if there are a lot of results if he is using a not too specific search term

Keep up the great work!

**Comment by sahedw** [comment]
> Great user story and really nice designs 🚀😊 Three things came to my mind when reading this US which you might want to consider as additional UX enahncement in this or another US:
> 
> * Adding logic that if the user can not go to next page if there are no more movies or back if the use is on page 1 would be nice
> * Currently when searching a movie and no results are found the user is brought to an empty page. In general a note what the user searched for would be nice so he can see directly if there are maybe any typos and additionally some "nice" empty state message would be cool if there are no results to be shown due to the search request
> * Some information how many movies were found in total would be great but not sure if your API is providing this information respectively if you can show it like this with pagination. Like this the user knows if there are a lot of results if he is using a not too specific search term
> 
> Keep up the great work!

I just pushed a new PR and I included your feedback and all your suggestions. Thanks a lot 🙌🏼
