### ISSUE TITLE
Search results details

### ISSUE THREAD

**Issue by sahedw** [sahedw/capstone-movie-app#5]
## Value Proposition

**As a user**
**I want to see short infos for every search result like the title, release year, genres and runtime.**  
**so that I can get a quick overview of the search result details without clicking on the movie/show**   
​

## Description

<img width="289" alt="Bildschirm­foto 2023-03-15 um 15 01 03" src="https://user-images.githubusercontent.com/122886715/225332358-abfd628e-c773-4209-aec1-f0a03f80afee.png">

## Acceptance Criteria

- [ ] Search results are shown with details
- [ ] Details include title, release year, genres and runtime.
      ​

## Tasks

- [ ] Use the mapped data from the fetch to not only include the poster/image but also the details which are requested
