### ISSUE TITLE
Rating a movie in watched

### ISSUE THREAD

**Issue by sahedw** [sahedw/capstone-movie-app#50]
## Value Proposition

**As a user**
**I want to rate the movies I have watched with starts out of five. I also want to leave a comment/note for myself**
**so that I can always go back to a movie in my list and see how I rated it and what I had to say about that movie**
​

## Description
​
<img width="278" alt="Bildschirm­foto 2023-04-03 um 09 17 56" src="https://user-images.githubusercontent.com/122886715/229447615-d1cd1bcb-01d2-41e4-a23c-b08cac16cd97.png">

## Acceptance Criteria

- [ ] If a movie is in the watched list of you, you can see some new content unter the poster
- [ ] A new 5 star rating where you can rate the movie
- [ ] Comment section to leave a comment for the watched movie
- [ ] A button to submit and save the stars/comments
      ​

## Tasks

- [ ] Conditional rendering of component if in watched
- [ ] Create form with rating
- [ ] Input textarea for comment
- [ ] Submit button
- [ ] Handle via state to save with possibly localStorage
      ​

## Complexity

XL
