### ISSUE TITLE
Styling of Movie Details Component

### ISSUE THREAD

**Issue by sahedw** [sahedw/capstone-movie-app#53]
## Value Proposition

**As a user**
**I want to look at visually appealing details which are structured of a movie**
**so that I feel comftable while being on that page**
​

## Description

​<img width="276" alt="Bildschirm­foto 2023-04-04 um 17 20 41" src="https://user-images.githubusercontent.com/122886715/229840127-7a7ae95b-a628-475e-8035-a63742beaf71.png">

<img width="280" alt="Bildschirm­foto 2023-04-04 um 17 20 47" src="https://user-images.githubusercontent.com/122886715/229840116-ed732928-033d-4fc6-97ff-980fe77f88d3.png">

## Acceptance Criteria

- [x] The movie detail page seems styled
      ​

## Tasks

- [x] Style the backbutton with styled components
- [x] Style the movie content with styled components and flexbox/grid
      ​

## Complexity

L
