### ISSUE TITLE
Search for shows and add to watchlist/watched

### ISSUE THREAD

**Issue by sahedw** [sahedw/capstone-movie-app#55]
## Value Proposition

**As a user** 
**I want to also search for shows and save them in my lists** 
**so that I can look up informations of shows and also keep track of them**
​

## Description

<img width="268" alt="Bildschirm­foto 2023-04-05 um 15 53 22" src="https://user-images.githubusercontent.com/122886715/230102757-732b3aed-d9e0-4542-8b10-0196af75cd63.png">

## Acceptance Criteria

- [x] You can decide if you want to search for a movie or a show with a click
- [x] One option always needs to be selected before search
- [x] Searching with the option "shows" selected should display the desired shows
- [x] Clicking on a show should lead to more informations
- [x] You're able to save them to watchlist or watched
      ​

## Tasks

- [x] Adapt the form to include two radio buttons which keep track of which medium should be searched for
- [x] Look how the movie objects and show object differ for further adaptation of components etc.
- [x] Check if the fuctionality of search is enough to also get into show details with a click and save them to your lists.
      ​

## Complexity

L

**Comment by lenzloesche** [comment]
"wanna" is not the appropriate language for a business paper. :) How about:
"There is a radio button for movies and shows under the Input field."
"Searching **for a** with the option shows should display the desired shows" this sentence doesn't make sense.

**Comment by sahedw** [comment]
> "wanna" is not the appropriate language for a business paper. :) How about: "There is a radio button for movies and shows under the Input field." "Searching **for a** with the option shows should display the desired shows" this sentence doesn't make sense.

Appreciate the feedback! I corrected the "wanna" and also the sentence which didn't make any sense. 
I couldn't take your suggestion because the acceptance criteria should have no developer specific terms like "radio button" or "input field".

Fixed with your help 😄
