### ISSUE TITLE
Animations

### ISSUE THREAD

**Issue by sahedw** [sahedw/capstone-movie-app#58]
## Value Proposition

**As a user**
**I want to see eye-catching and eye-pleasing animations** 
**so that the whole app looks beautiful, interactive and exciting**
​

## Description

Just a few animations for the movie/show posters, search results and the movie detail page. 
Mostly for smoothness and concealing loading time etc.
​

## Acceptance Criteria

- [ ] On the landing page the movie (if any movies are in your watchlist) are animated on load.
- [ ] After searching for a movie/show the search results fade in animated
- [ ] After clicking on a movie the movie detail page is also animated
- [ ] If the movie/show is added or removed from watchlist or watched with the buttons a small loading animation is displayed within the button to fake processing.
- [ ] Same animation for watchlist, watched and cinema page
      ​

## Tasks

- [ ] Create keyframes
- [ ] Create styled components
- [ ] Create functions and loading spinner if button to add/remove is clicked
      ​

## Complexity

L

**Comment by DominicWebDev** [comment]
both US LGTM
