### ISSUE TITLE
Save lists in mongoDB/Backend

### ISSUE THREAD

**Issue by sahedw** [sahedw/capstone-movie-app#59]
## Value Proposition

**As a user** 
**I want to have access to the saved movies/shows throughout all devices**
**so that I'm not bound to my handy or laptop**
​

## Description

Save the four lists (TV only contains shows):
- Watchlist
- WatchlistTV
- Watched
- WatchedTV

in a mongoDB-Database.
Use CRUD instead of current method of useLocalStorageState.
​

## Acceptance Criteria

- [ ] Adding movies to lists (watched/watchlist) still displays them in the respective pages/lists
- [ ] Same with removing
- [ ] Should be consistent throughout all devices
      ​

## Tasks

- [ ] Setup mongoDB compass for testing READ from DB
- [ ] Create functionality for CREATE and DELETE from DB
      ​

## Complexity

XL

**Comment by DominicWebDev** [comment]
LGTM
