### ISSUE TITLE
Movie Detail Page

### ISSUE THREAD

**Issue by sahedw** [sahedw/capstone-movie-app#6]
## Value Proposition

**As a user**
**I want to see more informations regarding a movie/show when I click on it**
**so that I can get a more precise impression of the movie/show**
​

## Description

​
<img width="331" alt="Bildschirm­foto 2023-03-15 um 15 47 31" src="https://user-images.githubusercontent.com/122886715/225353981-a156c58b-b4c8-4058-98e4-ef4e414f6c3b.png">

## Acceptance Criteria

- [ ] Describe every scenario in detail
- [ ] e.g. all inputs are required, show warning if empty.
- [ ] The poster is visible
- [ ] The title is visible
- [ ] The release year is visible
- [ ] The runtime is visible
- [ ] The actors are visible
- [ ] The plot is visible
- [ ] The popularity is visible
- [ ] Availability on different platforms is shown 
      ​

## Tasks

- [ ] Create a page which responds to the router.query 
- [ ] Catch unavailable routes 
- [ ] Display the movie details of the movie id which is in the url/router.query
- [ ] Add respective poster, title, release year, runtime, actors, plot, popularity etc.
- [ ] Add availability
      ​
