### ISSUE TITLE
Basic Search

### ISSUE THREAD

**Issue by sahedw** [sahedw/capstone-movie-app#7]
## Value Proposition

**As a user** 
**I want to be able to search for movies**
**so that I'm able to see which movies there are for my search** 
​

## Description

<img width="327" alt="Bildschirm­foto 2023-03-16 um 18 25 24" src="https://user-images.githubusercontent.com/122886715/225702594-13e55c5e-2462-4e72-bdd8-f06017792643.png">

## Acceptance Criteria

- [ ] Able to type in the search field
- [ ] Not being able to search without text in the search field
- [ ] Able to submit the search 
- [ ] Get search results shown as posters of the respective content
      ​

## Tasks

- [ ] Create a form with label and input
- [ ] Fetch the API with useEffect or with useSWR? Research
- [ ] Fetch the data with the input value and use it for the api search query
- [ ] Map through the fetched data and display the movie/show poster as an Image
      ​

## Complexity

S-M
