### ISSUE TITLE
Search results page

### ISSUE THREAD

**Issue by sahedw** [sahedw/capstone-movie-app#8]
## Value Proposition

**As a user** 
**I want to see my search results on a different page instead of the lading page** 
**so that I can get to see more search results without the search taking up space**  
​

## Description

<img width="366" alt="Bildschirm­foto 2023-03-16 um 18 39 19" src="https://user-images.githubusercontent.com/122886715/225706681-7db62595-c6bc-45db-bf1d-92e85a253cf2.png">

## Acceptance Criteria

- [ ] After clicking on search you get forwarded to a separate page
- [ ] It displays all the search results as posters on that page
- [ ] Being able to return to the initial page with a click
      ​

## Tasks

- [ ] After submitting the form push user to separate page with nextjs
- [ ] Display the state containing all the fetched data
- [ ] create cards which display only the poster as of right now
- [ ] create a button which leads back to the search input field
      ​

## Complexity

M
