### ISSUE TITLE
Search results quick overview

### ISSUE THREAD

**Issue by sahedw** [sahedw/capstone-movie-app#9]
## Value Proposition

**As a user**
**I want to see short and few details of the movies in my search results ** 
**so that I can quickly sort out which movies I'm not interested in without clicking on it** 
​

## Description

<img width="336" alt="Bildschirm­foto 2023-03-16 um 18 54 26" src="https://user-images.githubusercontent.com/122886715/225710359-f5161a16-fbd1-4517-a51a-4fb5306abdab.png">

## Acceptance Criteria

- [ ] After the search the results should be listed below each other 
- [ ] Each movie should show besides it the title, release year, genres and runtime.
      ​

## Tasks

- [ ] Design with css flexbox boxes which are positioned below each other.
- [ ] Place the poster on the far left and the respective details on the far right 
      ​

## Complexity

M
